name: frida-forcing
channels:
  - conda-forge
  - chrisroadmap
dependencies:
  - fair==2.1.0
  - ipython
  - ipywidgets
  - matplotlib
  - nbstripout
  - notebook
  - numpy
  - openpyxl
  - pandas
  - scipy
  - statsmodels
  - tqdm
